version: '2'

services:
    zookeeper:
        image: docker.io/bitnami/zookeeper:3.7
        ports:
            - '2181:2181'
        volumes:
            - 'zookeeper_data:/bitnami'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        image: docker.io/bitnami/kafka:2
        ports:
            - '9092:9092'
        volumes:
            - 'kafka_data:/bitnami'
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
    kafka-producer:
        image: learnwithvinod/kafka-producer:latest
        ports:
            - '8000:8000'
    kafka-consumer:
        image: learnwithvinod/kafka-consumer:latest
        ports:
            - '8001:8001'
volumes:
    zookeeper_data:
        driver: local
    kafka_data:
        driver: local
